### ISSUE TITLE
Gluc -> F16B not drawn correctly

### ISSUE THREAD

**Issue by hsauro** [0u812/sbnw#20]
Gluc -> F16B not drawn correctly

Should be:

Gluc + ATP -> F16B + ADP

**Comment by 0u812** [comment]
Upon closer inspection, this is a problem in the Jana Wolf model, not my code. It is missing a `modifierSpeciesReference` for ATP in the reaction. If a species is going to be used as a modifier (e.g. an inhibitor) in the layout, it must be declared as a modifier in the model. To do otherwise is inconsistent, and I believe that the solution is to fix the model.
